### ISSUE TITLE
Switch to TED API

### ISSUE THREAD

**Issue by moreginger** [moreginger/xbmc-plugin.video.ted.talks#16]
TED have an [API program](http://labs.ted.com/?page_id=14)

This looks great and would bring many benefits, e.g.:
- fixed interface = no scraper patches
- trivial search implementation
- easier to grab subtitles
- less hammering of TED website
- almost certainly much faster
- etc

Sadly, at the moment they are offering just 50 API keys to worthy original projects. I applied for a key on 5th April; so here's hoping - despite the obvious unoriginality of this preexisting project ;)

**Comment by amykyta3** [comment]
Looks like this can be closed.
http://developer.ted.com/?page_id=14
Shows that they are no longer continuing with the API effort.

**Comment by moreginger** [comment]
Thanks, good spot! I hope it isn't a bad sign for the future of open access to their data.
