### ISSUE TITLE
Add to Favorites

### ISSUE THREAD

**Issue by inDDev** [moreginger/xbmc-plugin.video.ted.talks#42]
Hi,
This isnt as much an issue as it is a way to workaround issues such as no download, broken favorites & queuing.
If there was a right click option to add a video from the list to the user's favorites, it would help a lot. Then if one really wants to download at least there is an option to track down the video from ted.com.
Great work on the add on otherwise!
Looking forward to your feedback!
Best
Ketan

**Comment by moreginger** [comment]
No plans to implement this.
