### ISSUE TITLE
Not showing anything in Search, Speakers, and Topics

### ISSUE THREAD

**Issue by Legionof7** [moreginger/xbmc-plugin.video.ted.talks#57]
When I click on one of those menus, nothing shows up. In search it will say Get More after you search something. New Videos still works.

**Comment by moreginger** [comment]
Thanks. I'm glad something works :+1: 
I guess TED changed their website again... should be able to look into it this week.

**Comment by Legionof7** [comment]
Alright, thanks! :) It might be my system, I'll check some things.

**Comment by moreginger** [comment]
Found and fixed issues with search and topics, speakers seemed fine for me...

4.2.8 should hopefully wing its way to you in the next couple of days

Thanks for reporting :+1:

**Comment by Legionof7** [comment]
Yeah, I figured Speakers out. Thanks!

**Comment by gibxxi** [comment]
For me (in v5.0.1) and the Kodi repo version, Topics are blank again (only thing displayed being an ellipsis). Speakers comes up with numerical groups which all seem to list the same list of speakers for each numerical group (1-4, 4-8, etc, etc.) as well.
