### ISSUE TITLE
Ted Talks stopped working suddenly

### ISSUE THREAD

**Issue by dencrypt** [moreginger/xbmc-plugin.video.ted.talks#73]
Plugin seems to have stopped working today for no apparent reason. My initial thought is that the API has changed on the TED side and the plugin can therefor no longer retrieve videos.
[kodi.log](https://github.com/moreginger/xbmc-plugin.video.ted.talks/files/3195023/kodi.log)

Using Kodi 18.1 in Manjaro

**Comment by moreginger** [comment]
Appreciate the heads up!
I'll look into this. I don't have a dev environment set up for Kodi though, and I see they have stipulated migration to Python 3 compatible code so it will take me a few days.

**Comment by gedakc** [comment]
Yesterday I downloaded a copy of the **develop** branch and confirmed that the updates contained within enable the playback of Ted Talks again.  :-)

**Comment by moreginger** [comment]
Thanks for testing. I'm trying to [get this in the main repo](https://github.com/xbmc/repo-plugins/pull/2410) now.
