### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by rikardfries** [moreginger/xbmc-plugin.video.ted.talks#76]
Is there a Matrix version of this addon ? 
It seems to be Python 3 compatible but has an old requirement for python,

**Comment by moreginger** [comment]
Thanks for the heads up, I don't keep tabs on Kodi at the moment so I hadn't realised that the hard Python 3 requirement was here. My recollection was this is was almost there but that I had a few issues still... I'll need to have a look.

**Comment by rikardfries** [comment]
> Thanks for the heads up, I don't keep tabs on Kodi at the moment so I hadn't realised that the hard Python 3 requirement was here. My recollection was this is was almost there but that I had a few issues still... I'll need to have a look.

Perfect thank you.!

**Comment by rikardfries** [comment]
It also demanded elementtree which I think is in python nowadays and then parsedom.
Parsedom I do not know anything about..

**Comment by moreginger** [comment]
parsedom hasn't been ported to Matrix yet. There is some discussion [here](https://forum.kodi.tv/showthread.php?tid=348400&pid=2987425#pid2987425) so we'll see what comes of it.
